### PR TITLE
Fix Python 3 compatibility.

### PR DESCRIPTION
**Pull request by ProgVal**
Added compatibility to run mine.py as-is with Python 3.
Of course, I did not break Python 2 compatibility.

### CODE REVIEW

**Comment by ocarneiro** [comment]
There's a better (IMHO) way to make it Python 2 and 3 compatible using the [future module](http://python-future.org/compatible_idioms.html).

**Comment by ProgVal** [comment]
@ocarneiro My solution does not add an external dependency, and is not harder to read than using six.

**Comment by tleeuwenburg** [comment]
Does this still need to be done? I did a simple 2to3 on my machine and basically it worked after some edits where ints were expected. I would find it straightforward to write a version than can run as 2 or 3 (e.g. import range as xrange or similar). I haven't reviewed anyones pre-existing code, I'd be happy to pick a pre-existing solution and tweak it into shape.

The only issue I found was that the blocks don't render initially. I think there's some bug in terms of deciding what's exposed and what's not. If I add a block, that works fine. If a delete a block, all the adjacent exposed blocks become visible.

**Comment by ProgVal** [comment]
> I did a simple 2to3 on my machine and basically it worked after some edits where ints were expected.

With this PR, 2to3 is not needed.
And the ints thing is half of the content of the PR.

> I would find it straightforward to write a version than can run as 2 or 3 (e.g. import range as xrange or similar).

That's exactly what this PR does

> The only issue I found was that the blocks don't render initially. I think there's some bug in terms of deciding what's exposed and what's not. If I add a block, that works fine. If a delete a block, all the adjacent exposed blocks become visible.

What do you mean by “exposed”? I don't see a difference in behavior between running on Python 2 or 3.

**Comment by ProgVal** [comment]
@fogleman Thanks!

**Pull request merged**
